fix: pass expected variable
Previously, tests failed with
TypeError: iter_subproc() got an unexpected keyword argument 'input'

because a previously used implementation of iter_git_subproc
had input as a parameter name. The now used implementation
in datasalad renamed this parameter to inputs.

I'm not sure if this causes other problems down the line
because I believe different runners not inconsistently
expect either input or inputs...